version: '3.9'

services:
  users.db:
    image: postgres
    container_name: users.db
    ports:
      - "5432:5432"
  
  users.api:
    container_name: users.api
    build:
      context: .
      dockerfile: Server/src/Services/Users/Users.API/Dockerfile
    ports:
      - "8080:8080"

volumes:
  users_data:
    name: users_data

