version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - ./ecommercedb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: ecommercedb
