version: '3.9'

services:
  messagebroker:
    image: rabbitmq:management
  
  users.db:
    image: postgres
    container_name: users.db
    ports:
      - "5432:5432"
  
  catalog.db:
    image: postgres
    container_name: catalog.db
    ports:
      - "5431:5432"
        
  ordering.db:
    image: postgres
    container_name: ordering.db
    ports:
      - "5430:5432"
        
  distributed.cache:
    image: redis
  
  users.api:
    image: users.api
    container_name: users.api
    build:
      context: .
      dockerfile: Server/src/Services/Users/Users.API/Dockerfile
    ports:
      - "8080:8080" 
        
  users.smtp:
    image: changemakerstudiosus/papercut-smtp:latest
    ports:
      - "25:25"
      - "2525:80"

  catalog.api:
    image: catalog.api
    container_name: catalog.api
    build:
      context: .
      dockerfile: Server/src/Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "7080:7080"

  ordering.api:
    image: ordering.api
    container_name: ordering.api
    build:
      context: .
      dockerfile: Server/src/Services/Ordering/Ordering.API/Dockerfile
    ports:
      - "6080:6080"
        
  yarpgateway:
    image: yarpgateway
    container_name: yarpgateway
    build:
      context: .
      dockerfile: Server/src/APIGateways/YarpGateway/Dockerfile
    ports:
      - "9080:9080"

volumes:
  users_data:
    name: users_data
  catalog_data:
    name: catalog_data
  ordering_data:
    name: ordering_data
  message_broker_data:
    name: message_broker_data
  message_broker_log:
    name: message_broker_log

